### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by maximeLabelbox** [mistralai/mistral-src#3]
Congrats on the launch! 

I'm on Mac M1 and I'm getting this error related to Torch not compiled with CUDA enabled.
I'm guessing that CUDA is not supported on the Mac chips. 
Any idea how I can get around this? 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/.../Mistral_github/mistral-src/main.py", line 134, in <module>
    fire.Fire({
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/.../fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/.../Mistral_github/mistral-src/main.py", line 116, in demo
    transformer = Transformer.from_folder(Path(model_path), max_batch_size=3)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../Mistral_github/mistral-src/mistral/model.py", line 220, in from_folder
    model = Transformer(model_args).to(device=device, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../Mistral_github/mistral-src/mistral/model.py", line 185, in __init__
    self.freqs_cis = precompute_freqs_cis(self.args.head_dim, 128_000).to("cuda")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```

**Comment by RiadM** [comment]
This worked for me but didn't try on a Mac.
[Removing and then reinstall](Removinhttps://stackoverflow.com/questions/75752503/error-torch-not-compiled-with-cuda-enabled)

**Comment by shakfu** [comment]
I had the same problem, this doesn't look it works on macOS since the [coda toolkit is only linux / windows](https://developer.nvidia.com/cuda-downloads)

**Comment by 0smboy** [comment]
@maximeLabelbox Your M1 Mac does not have Cuda, which is a feature of Nvidia GPUs. try use .to("mps") instead of to("cuda")

**Comment by timlacroix** [comment]
Ah yeah this repo definitely requires CUDA. 
If the goal is to run the model locally, maybe have a look at https://github.com/ggerganov/llama.cpp ?
